[plugins]

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jooq = { id = "nu.studer.jooq", version.ref = "jooq" }
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }
versions = { id = "com.github.ben-manes.versions", version = "0.51.0" }
taskinfo = { id = "org.barfuin.gradle.taskinfo", version = "2.2.0" }

[versions]

kotlin = "2.0.21"
jooq = "9.0"
flyway = "9.22.3"
junit = "5.11.3"
jackson = "2.18.1"
postgresql = "42.7.4"
coroutines = "1.9.0"
result4k = "2.20.0.0"
slf4j = "2.0.16"
http4k = "5.33.1.0"
hikaricp = "6.1.0"
jooq-core = "3.19.15"
kotlinx-html = "0.11.0"
strikt = "0.35.1"
playwright = "1.48.0"

[libraries]

kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
result4k = { module = "dev.forkhandles:result4k", version.ref = "result4k" }
slf4j = { module = "org.slf4j:slf4j-jdk14", version.ref = "slf4j" }

http4k-bom = { module = "org.http4k:http4k-bom", version.ref = "http4k" }
http4k-core = { module = "org.http4k:http4k-core" }
http4k-server-undertow = { module = "org.http4k:http4k-server-undertow" }
http4k-config = { module = "org.http4k:http4k-config" }
http4k-client-apache = { module = "org.http4k:http4k-client-apache" }
http4k-testing-approval = { module = "org.http4k:http4k-testing-approval" }
http4k-testing-hamkrest = { module = "org.http4k:http4k-testing-hamkrest" }
http4k-testing-strikt = { module = "org.http4k:http4k-testing-strikt" }

jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-module-parameter-names = { module = "com.fasterxml.jackson.module:jackson-module-parameter-names", version.ref = "jackson" }
jackson-datatype-jdk8 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jdk8", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }

postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }

jooq = { module = "org.jooq:jooq", version.ref = "jooq-core" }
kotlinx-html = { module = "org.jetbrains.kotlinx:kotlinx-html-jvm", version.ref = "kotlinx-html" }

junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

strikt = { module = "io.strikt:strikt-core", version.ref = "strikt" }
playwright = { module = "com.microsoft.playwright:playwright", version.ref = "playwright" }
